spring:
  r2dbc:
    url: r2dbc:tc:mysql:///AUTHABLE?TC_IMAGE_TAG=8.0.33-debian

#testcontainers:
#  reuse:
#    enable: true

infrastructure-coredb:
  system-id-padding: 5
  totp-user-id-padding: 50

