spring:
  r2dbc:
    url: r2dbc:mariadb://${COAUTH_DB_IP}:${COAUTH_DB_PORT}/COAUTH?allowPublicKeyRetrieval=true
    username: ${COAUTH_DB_USERNAME}
    password: ${COAUTH_DB_PASSWORD}
    pool:
      initial-size: 1
      max-size: 5
      max-idle-time: 30m
      validation-query: SELECT 1

infrastructure-coredb:
  system-id-padding: 5
  totp-user-id-padding: 50
