spring:
  config:
    import: application-rest.yml,domain.yml,infrastructure-coredb.yml,infrastructure-crypto.yml
  jpa:
    show_sql: true
    format_sql: true

logging:
  level:
    root: DEBUG
    org:
      springframework:
        security: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE